### ISSUE TITLE
Documentation for TripletBinaryDataLayer

### ISSUE THREAD

**Issue by gavinmh** [wanji/caffe-sl#4]
Hello,

What is the format expected by the TripletBinaryDataLayer? From what I can tell, the only documentation for this layer is `@brief Provides triplet data to the Net from binary files.`

Thanks,
Gavin

**Comment by wanji** [comment]
It requires a folder which is similar as expected by the ImageDataLayer, except that:
1. there is a file named `meta` under that folder
2. the folder consists of binary files instead of images

here is an example of the `meta` file

```
float32
32 64 112 112
```

The first line specify the data type of the binary files [only float32 supported in the current implementation]
The second line is the shape of the data blob: batch size, channels, height, width.

In this case, each binary file contains `64 * 112 * 112` single float numbers.

**Comment by gavinmh** [comment]
Thanks @wanji !
