### ISSUE TITLE
LMDB support in TripletImageDataLayer

### ISSUE THREAD

**Issue by ergysr** [wanji/caffe-sl#6]
I have been using the TripletImageData layer for training and testing and it works fine on the mnist_sl example. However, when training with a bigger network and with a large number of images the TripletImageData layer creates an IO bottleneck that makes training slow. Is there already a way to convert triplet list files into lmdb databases and use those instead of the text files that point to images on disk?

**Comment by wanji** [comment]
As the triplets are random combination of images, it requires a huge amount of disk space for storing all the triplet input data.
Usually the data layer should not be an bottleneck because of the data prefetching mechanism. If you are sure that this layer creates the IO bottleneck, may be you can preload all the images and generate triplet input data in memory. Alternatively, you can create small batches as mentioned in [FaceNet](http://arxiv.org/abs/1503.03832), that should be more suitable for LMDB databases.
